version: 2
jobs:
  deploy:
    working_directory: ~/NativescriptAppBuild
    docker:
      - image: circleci/node:13.0
    steps:
      - checkout

      - run:
          name: Install npm modules
          command: |
            sudo npm i -g firebase-tools --ignore-scripts --unsafe-perm --no-progress;
            npm i --no-progress;

      - run:
          name: Check for Firestore updates
          command: |
            ./IsFirestoreUpdates.sh

      - run:
          name: Deploy to dev
          command: |
            firebase use ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOOLS_TOKEN}
            firebase deploy -m "Deploying ${CIRCLE_SHA1} commit by ${CIRCLE_USERNAME} ${CIRCLE_BUILD_URL}" --token ${FIREBASE_TOOLS_TOKEN}

workflows:
  version: 2
  build_release:
    jobs:
      - deploy
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /.*/
