version: 2
jobs:
  deploy:
    working_directory: ~/ciDeployment
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout

      - run:
          name: Install npm modules
          command: |
            sudo npm i -g prettier standard firebase-tools --ignore-scripts --unsafe-perm --no-progress;
            npm i --no-progress;
            cd functions && npm i --no-progress && cd ../;

      - run:
          name: Functions standard JS
          command: |
            cd functions && npm run standardfix && cd ../;

      - run:
          name: Functions lint
          command: |
            cd functions && npm run lintfix && cd ../;

      - run:
          name: Check for Firestore updates
          command: |
            ./scripts/IsFirestoreUpdates.sh

      - run:
          name: Update version in Config.js for POM
          command: |
            sed -i 's/{{APP_VERSION_HERE}}/'${CIRCLE_SHA1:(-10)}'/g' hosting/POM/js/src/config.js

      - run:
          name: style check POM
          command: |
            ./scripts/standardStylePOM.sh

      - run:
          name: build POM js modules
          command: |
            ./scripts/buildPOM.sh


      - run:
          name: Update version in Config.js for site
          command: |
            sed -i 's/{{APP_VERSION_HERE}}/'${CIRCLE_SHA1:(-10)}'/g' hosting/site/js/src/config.js

      - run:
          name: style check site
          command: |
            ./scripts/standardStyleSite.sh

      - run:
          name: build site js modules
          command: |
            ./scripts/buildSite.sh

      - run:
          name: Deploy to dev
          command: |
            firebase use ${FIREBASE_PROJECT_ID} --token ${FIREBASE_TOOLS_TOKEN}
            ./scripts/do-exclusively firebase deploy -f -m "(CircleCI) ${CIRCLE_SHA1} commit by ${CIRCLE_USERNAME} ${CIRCLE_BUILD_URL}" --token ${FIREBASE_TOOLS_TOKEN}

workflows:
  version: 2
  build_release:
    jobs:
      - deploy
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /.*/
