version: 2
jobs:
  deploy:
    working_directory: ~/NativescriptAppBuild
    docker:
      - image: circleci/node:13.0
    steps:
      - checkout

      - run:
          name: Install npm modules
          command: |
            sudo npm i -g firebase-tools --ignore-scripts --unsafe-perm --no-progress;
            npm i --no-progress;

      - run:
          name: Check for Firestore updates
          command: |
            ./UpdateFirestore.sh

workflows:
  version: 2
  build_release:
    jobs:
      - deploy
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /.*/
